export const PropertyTypeOptionsData = [
  {
    group: "Residential",
    items: [
      "Flat/Apartment",
      "Residential House",
      "Villa",
      "Builder Floor Apartment",
      "Residential Land/Plot",
      "Penthouse",
      "Studio Apartment",
    ],
  },
  {
    group: "Commercial",
    items: [
      "Commercial Office Space",
      "Office in IT/SEZ",
      "Commerical Shop",
      "Commercial Showroom",
      "Warehouse/Godown",
      "Industrial Land",
      "Industrial Building",
      "Industrial Shed",
    ],
  },
  {
    group: "Agricultural",
    items: ["Agricultural Land", "Farm House"],
  },
];

export const cityData = [
  "Bhopal",
  "Indore",
  "Gwalior",
  "Jabalpur",
  "Ujjain",
  "Satna",
  "Rewa",
  "Sagar",
  "Ratlam",
  "Chhindwara",
  "Dewas",
  "Khandwa",
  "Khargone",
  "Shivpuri",
  "Chhatarpur",
  "Betul",
  "Vidisha",
  "Hoshangabad",
  "Dhar",
  "Sehore",
  "Mandsaur",
  "Neemuch",
  "Balaghat",
  "Katni",
  "Shahdol",
  "Itarsi",
  "Panna",
  "Bhind",
  "Morena",
  "Singrauli",
  "Mandla",
  "Damoh",
  "Ashoknagar",
  "Barwani",
  "Harda",
  "Rajgarh",
  "Sheopur",
  "Narsinghpur",
  "Tikamgarh",
  "Anuppur",
  "Umaria",
];

export const localitiesInBhopalData = [
  "Arera Colony",
  "Shahpura",
  "MP Nagar",
  "Kolar Road",
  "Hoshangabad Road",
  "Bawadia Kalan",
  "Berasia",
  "Bairagarh",
  "Chuna Bhatti",
  "Bagh Mugaliya",
  "Misrod",
  "Indrapuri",
  "Ayodhya Nagar",
  "Gulmohar Colony",
  "Awadhpuri",
  "Rohit Nagar",
  "Shyamla Hills",
  "Kohefiza",
  "Jahangirabad",
  "Nehru Nagar",
  "Old City",
  "Govindpura",
  "Karond",
  "Ashoka Garden",
  "Piplani",
  "Rajharsh Colony",
  "Habibganj",
  "Kalpana Nagar",
  "Alkapuri",
  "Sarvadharam Colony",
  "Kasturba Nagar",
  "Patel Nagar",
  "Vidya Nagar",
  "Tulsi Nagar"
];
